name: newflutterapp
description: A new Flutter application.
version: 1.0.0+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.16.1
  flutter_facebook_login: ^3.0.0
  image_picker:  ^0.6.7+4
  google_sign_in: ^4.5.1
  flutter_signin_button: ^1.0.0
  url_launcher: ^5.2.5
  firebase_core: ^0.4.5
  modal_progress_hud: ^0.1.3
  cloud_firestore: ^0.13.7
  cloud_firestore_web: ^0.1.1+2

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/


